name: "Infra"

on:
  workflow_dispatch:
    inputs:
      manual_path:
        description: 'Provided paths (comma-separated if multiple) without "/" at beggining.'
        required: false

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '*/*/*/init/**'

  push:
    branches:
      - '**'
    paths-ignore:
      - '*/*/*/init/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  matrix:
    uses: ./.github/workflows/generate_matrix.yaml
    with:
      manual_paths: ${{ github.event.inputs.manual_path }}
      filter: "infra"
      file_patterns: |
        **.tf
        **.hcl
        **.tfvars
        !*/*/*/init/**

  terraform:
    if: ${{ needs.matrix.outputs.matrix != '{"include":[]}' && needs.matrix.outputs.matrix != '' }}
    name: "${{ matrix.workspace }}/${{ matrix.region }}/${{ matrix.cluster }}"
    needs: matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    environment: "${{matrix.workspace}}-${{matrix.region}}-${{matrix.cluster}}"
    env:
      TF_WORKSPACE: "${{matrix.workspace}}-${{matrix.region}}-${{matrix.cluster}}"
      WORK_DIR: "${{ matrix.workspace }}/${{ matrix.region }}/${{ matrix.cluster }}/${{ matrix.workdir }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo variables
        run: |
          echo "Workspace: ${{ matrix.workspace }}"
          echo "Region: ${{ matrix.region }}"
          echo "Cluster: ${{ matrix.cluster }}"
          echo "Workdir: ${{ matrix.workdir }}"
